version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm

    working_directory: ~/repo/client

    steps:
      - checkout:
          path: ~/repo

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install 

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run test
