/**
 * This file was automatically generated by Nexus 0.11.7
 * Do not make changes to this file directly
 */

import * as ctx from "./types"
import * as entity_line from "./entity/line"
import * as entity_post from "./entity/post"
import * as entity_tweet from "./entity/tweet"
import * as entity_user from "./entity/user"
import { core } from "nexus"
declare global {
  interface NexusGenCustomDefinitionMethods<TypeName extends string> {
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Date";
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  LineInput: { // input type
    id?: string | null; // ID
    partialLines: NexusGenInputs['PartialLineInput'][]; // [PartialLineInput!]!
  }
  PartialLineInput: { // input type
    referes?: string[] | null; // [String!]
    subtext: string; // String!
  }
  PostInput: { // input type
    isDraft: boolean; // Boolean!
    language: number; // Int!
    lines: NexusGenInputs['LineInput'][]; // [LineInput!]!
  }
  SearchInput: { // input type
    language?: number | null; // Int
  }
  TweetInput: { // input type
    inReplyTo: string; // ID!
    postId: string; // ID!
    text: string; // String!
  }
  UserInput: { // input type
    email: string; // String!
    fluentLanguages: number[]; // [Int!]!
    learningLanguages: number[]; // [Int!]!
    username: string; // String!
  }
}

export interface NexusGenEnums {
}

export interface NexusGenRootTypes {
  AuthData: { // root type
    token: string; // String!
  }
  Language: { // root type
    id: string; // ID!
    name: string; // String!
  }
  Line: entity_line.Line;
  Mutation: {};
  PartialLine: { // root type
    text: string; // String!
  }
  Post: entity_post.Post;
  Query: {};
  Tweet: entity_tweet.Tweet;
  User: entity_user.User;
  Node: NexusGenRootTypes['Post'] | NexusGenRootTypes['Language'] | NexusGenRootTypes['Line'] | NexusGenRootTypes['Tweet'] | NexusGenRootTypes['User'];
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  Date: any;
  Repliable: NexusGenRootTypes['Line'] | NexusGenRootTypes['Tweet'];
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  LineInput: NexusGenInputs['LineInput'];
  PartialLineInput: NexusGenInputs['PartialLineInput'];
  PostInput: NexusGenInputs['PostInput'];
  SearchInput: NexusGenInputs['SearchInput'];
  TweetInput: NexusGenInputs['TweetInput'];
  UserInput: NexusGenInputs['UserInput'];
}

export interface NexusGenFieldTypes {
  AuthData: { // field return type
    token: string; // String!
  }
  Language: { // field return type
    id: string; // ID!
    name: string; // String!
  }
  Line: { // field return type
    id: string; // ID!
    partialLines: NexusGenRootTypes['PartialLine'][]; // [PartialLine!]!
    replies: NexusGenRootTypes['Tweet'][]; // [Tweet!]!
  }
  Mutation: { // field return type
    logout: boolean; // Boolean!
    postCreate: NexusGenRootTypes['Post']; // Post!
    postUpdate: NexusGenRootTypes['Post']; // Post!
    signin: NexusGenRootTypes['AuthData']; // AuthData!
    tweetCreate: NexusGenRootTypes['Tweet']; // Tweet!
    tweetLike: NexusGenRootTypes['Tweet']; // Tweet!
    userCreate: NexusGenRootTypes['User']; // User!
    userUpdate: NexusGenRootTypes['User']; // User!
  }
  PartialLine: { // field return type
    text: string; // String!
  }
  Post: { // field return type
    createdAt: any | null; // Date
    id: string; // ID!
    isDraft: boolean; // Boolean!
    json: string; // String!
    language: NexusGenRootTypes['Language']; // Language!
    lines: NexusGenRootTypes['Line'][]; // [Line!]!
    replies: NexusGenRootTypes['Tweet'][]; // [Tweet!]!
    title: string; // String!
    updatedAt: any | null; // Date
    user: NexusGenRootTypes['User']; // User!
  }
  Query: { // field return type
    feed: NexusGenRootTypes['Post'][]; // [Post!]!
    langs: NexusGenRootTypes['Language'][]; // [Language!]!
    post: NexusGenRootTypes['Post']; // Post!
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
    replies: NexusGenRootTypes['Tweet'][]; // [Tweet!]!
    search: NexusGenRootTypes['Post'][]; // [Post!]!
    tweet: NexusGenRootTypes['Tweet']; // Tweet!
    user: NexusGenRootTypes['User']; // User!
    viewer: NexusGenRootTypes['User']; // User!
  }
  Tweet: { // field return type
    createdAt: any | null; // Date
    id: string; // ID!
    inReplyTo: number | null; // Int
    likeCount: number; // Int!
    likedByMe: boolean; // Boolean!
    post: NexusGenRootTypes['Post']; // Post!
    postedBy: NexusGenRootTypes['User']; // User!
    replies: NexusGenRootTypes['Tweet'][]; // [Tweet!]!
    text: string; // String!
    updatedAt: any | null; // Date
  }
  User: { // field return type
    createdAt: any | null; // Date
    email: string; // String!
    fluentLanguages: number[]; // [Int!]!
    id: string; // ID!
    learningLanguages: number[]; // [Int!]!
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
    updatedAt: any | null; // Date
    username: string; // String!
  }
  Node: { // field return type
    id: string; // ID!
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    postCreate: { // args
      post: NexusGenInputs['PostInput']; // PostInput!
    }
    postUpdate: { // args
      id: string; // ID!
      post: NexusGenInputs['PostInput']; // PostInput!
    }
    signin: { // args
      token: string; // String!
    }
    tweetCreate: { // args
      tweet: NexusGenInputs['TweetInput']; // TweetInput!
    }
    tweetLike: { // args
      id: string; // ID!
    }
    userCreate: { // args
      id: string; // ID!
    }
    userUpdate: { // args
      id: string; // String!
      user: NexusGenInputs['UserInput']; // UserInput!
    }
  }
  Query: {
    feed: { // args
      uid: string; // String!
    }
    post: { // args
      id: string; // ID!
    }
    replies: { // args
      id: string; // ID!
    }
    search: { // args
      query: NexusGenInputs['SearchInput']; // SearchInput!
    }
    tweet: { // args
      id: string; // ID!
    }
    user: { // args
      username: string; // String!
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
  Repliable: "Line" | "Tweet"
  Node: "Post" | "Language" | "Line" | "Tweet" | "User"
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "AuthData" | "Language" | "Line" | "Mutation" | "PartialLine" | "Post" | "Query" | "Tweet" | "User";

export type NexusGenInputNames = "LineInput" | "PartialLineInput" | "PostInput" | "SearchInput" | "TweetInput" | "UserInput";

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = "Node";

export type NexusGenScalarNames = "Boolean" | "Date" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = "Repliable";

export interface NexusGenTypes {
  context: ctx.GraphQLContext;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}